version: '3'
services:
  wot:
    build: .
    restart: always
    environment:
     - TZ=Europe/Madrid
    ports:
     - 8484:8484
    depends_on:
     - rabbit

  rabbit:
    image: rabbitmq:3.7.5-management
    hostname: "rabbitmq"
    restart: always
    ports:
     - 5672:5672
     - 15672:15672
    environment:
     - RABBITMQ_DEFAULT_USER=venus
     - RABBITMQ_DEFAULT_PASS=venuspass
